name: CI/CD
on:
  pull_request:
    types: [opened, edited, synchronize, closed]
    branches: [main]

jobs:
  ci-check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  ci-check-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for hard-coded secrets
        id: secrets
        uses: trufflesecurity/trufflehog@v3.88.20

      - name: Scan for vulnerable code 
        id: code
        uses: bearer/bearer-action@v2
        with:
          diff: true
          severity: "critical,high"
          exit-code: "1"

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@0.28.0
        id: deps
        with:
          scan-type: "fs"
          scanners: "vuln,secret,misconfig"
          severity: "CRITICAL,HIGH"
          exit-code: "1"

  ci-tag-release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b #v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: Release ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
