name: CI/CD
on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]
  push:
    branches: [main]

jobs:
  check-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  check-security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Scan for hard-coded secrets
        id: secrets
        uses: trufflesecurity/trufflehog@v3.88.20

      - name: Scan for vulnerable code
        id: code
        uses: bearer/bearer-action@v2
        with:
          diff: true
          severity: 'critical,high'
          exit-code: '1'

      - name: Scan for vulnerable dependencies
        uses: aquasecurity/trivy-action@0.28.0
        id: deps
        with:
          scan-type: fs
          scanners: 'vuln,secret,misconfig'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

  release:
    needs: [check-lint, check-security]
    runs-on: ubuntu-latest
    permissions:
      contents: write # needs write permission to push tag and release
    steps:
      - uses: actions/checkout@v4

      - name: Set bump type
        id: bump
        env:
          # seem .commitlint for more details
          BUMP_MAJOR: 'major|breaking'
          BUMP_MINOR: 'minor|feat|ft'
          BUMP_PATCH: 'patch|fix|docs|chore'
          # set commit header as pr title if event is pull_request otherwise use latest commit message
          COMMIT_HEADER: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.event.head_commit.message }}
        run: |
          BUMP_TYPES="$BUMP_MAJOR|$BUMP_MINOR|$BUMP_PATCH"

          # only get the first line of the commit message
          COMMIT_HEADER=$(echo "$COMMIT_HEADER" | head -n 1)

          echo "::notice ::Calculating bump type based on commit header..."
          echo "::notice ::Commit Header: \"$COMMIT_HEADER\""

          # check that pr follows `<type>(<scope>): <description>` format
          if [[ ! $COMMIT_HEADER =~ ^($BUMP_TYPES)(\([a-zA-Z0-9_-]+\))?: ]]; then
            echo "::error ::Invalid Commit Header: Commit Header does not follow the conventional commit format of \`<type>(<scope?>): <description>\`."
            echo "::error ::Valid <type>: $BUMP_TYPES"
            echo "::error ::Tip: <scope> is optional."
            exit 1
          fi

          # set bump based on commit header
          if [[ $COMMIT_HEADER =~ ^($BUMP_MAJOR)(\([a-zA-Z0-9_-]+\))?: ]]; then
            BUMP='major'
          elif [[ $COMMIT_HEADER =~ ^($BUMP_MINOR)(\([a-zA-Z0-9_-]+\))?: ]]; then
            BUMP='minor'
          else
            BUMP='patch'
          fi

          echo "::notice ::Setting bump type: $BUMP"
          echo "type=$BUMP" >> $GITHUB_OUTPUT

      - name: Bump version and push tag (dry-run)
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        if: github.event_name == 'pull_request'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.bump.outputs.type }}
          dry_run: true

      - name: Bump version and push tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        id: tag
        uses: mathieudutour/github-tag-action@a22cf08638b34d5badda920f9daf6e72c477b07b # v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.bump.outputs.type }}

      - name: Create a GitHub release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          tag: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.tag.outputs.new_tag }}
          body: ${{ steps.tag.outputs.changelog }}
