name: Pull Request Reviewer

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches: [main]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title
        env:
          COMMIT_TYPE: 'major|breaking|release|minor|feat|ft|patch|fix|docs|chore'
          PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo "::notice title=Checking PR Title Formtat, $PULL_REQUEST_TITLE"

          # check that pr follows `<type>(<scope>): <description>` format
          if [[ ! $PULL_REQUEST_TITLE =~ ^($COMMIT_TYPE)(\([a-zA-Z0-9_-]+\))?: ]]; then
            echo "::error title=Invalid Pull Request Title::PR Title does not follow the conventional commit format of <type>(<scope>): <description>. The type must be one of the following: $COMMIT_TYPE."
            exit 1
          fi
